## spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(A43tEzFy1b8ZPqSuGFvu8A==)
      client-secret: ENC(AhqEIMhE3g8a/oViW3+RoA==)
      scope: server

# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ENC(IDmyJ4IXb7MptwbLev6ULA==) # mysql
    url: jdbc:mysql://sell-mysql:3306/sell?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  resources:
    static-locations: classpath:/static/,classpath:/views/

## 直接放行URL
#ignore:
#  urls:
#    - /actuator/**
