## spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(twuhCbvnzZwCREcO6fCgRQ==)
      client-secret: ENC(dYoyZAivLbX5O18a47d8uw==)
      scope: server

# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ENC(IDmyJ4IXb7MptwbLev6ULA1==) # mysql
    url: jdbc:mysql://sell-mysql:3306/sell?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true

# 直接放行URL
ignore:
  urls:
    - /actuator/**
    - /user/info/*
    - /log/**

test:
  config: sell-upms-config
